problem_parameters:
  battery_capacity: 3
  battery_efficiency: 1
  battery_initial_charge: 1
  battery_max_exchange: 1
  buy_price:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  load:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  num_slots: 8
  penalty_factor: 100000
  sell_price:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  solar:
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
qaoa_classical_optimizer:
  name: NELDER_MEAD
  parameters:
    maxiter: 1000
qaoa_parameters:
  reps: 5
random_data_generation:
  generate_random_data: true
  random_seed: null
